branches:
  only:
    - master

version: 0.1.0.{build}-rc

configuration: Debug

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

cache:
  - packages


nuget:
  disable_publish_on_pr: true
  
install:
    - nuget restore

build:
  project: Autohasher.sln
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  verbosity: minimal
#  verbosity: detailed
 
environment:
    COVERALLS_REPO_TOKEN: 
      secure: wW32TK+eBM0DYSJCf2YQFGuIpbRp3cWSeVEpa8qLh4jOUULGsLSytcI/aEZNrEza


after_test: 
    - packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[AutoHashing]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"AutoHasher.Test\bin\debug\AutoHasher.Test.dll /domain:single /noshadow" -output:"coverage.xml"

    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover "coverage.xml"
    

#
#before_deploy:
#  - nuget pack AutoHasher.nuspec -Version "%APPVEYOR_BUILD_VERSION%"
#  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }

deploy:
  provider: NuGet
  api_key:
     secure: iilt+MH/q6fzDsdRndFHjE9WawMnZAiGfcNfeRYf90R0Q2e50nUM8SZMfW2xgvBm
  skip_symbols: false
